-- EYIS System Seed — 003_product_blueprints: System-Produkt-Blueprints
--
-- ERZEUGT von scripts/installer/generate-system-seeds.ts. Nicht von Hand ändern.
-- Quelle: 20260825080717
-- Idempotent: mehrfaches Ausführen verändert nichts.

DO $eyis_seed$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.product_blueprints WHERE is_system) THEN
  INSERT INTO public.product_blueprints (key, name, description, icon, version, is_system, schema, variant_schema) VALUES
  ('standard','Standardprodukt','Für alles, was keine besonderen Branchenangaben braucht.','package',1,true,
   '{"groups":[{"key":"basis","label":"Produktdetails","fields":[{"key":"sku","type":"text","label":"Artikelnummer (SKU)","description":"Optional, wenn du mit Varianten arbeitest."},{"key":"barcode","type":"text","label":"Barcode / EAN"},{"key":"hinweise","type":"textarea","label":"Interne Hinweise"}]}]}'::jsonb,
   '{"axes":[]}'::jsonb),
  ('textil','Textilien','Kleidung und Stoffe mit Größen, Farben und Pflegehinweisen.','shirt',1,true,
   '{"groups":[{"key":"produkt","label":"Produktangaben","fields":[{"key":"marke","type":"text","label":"Marke"},{"key":"material","type":"text","label":"Material"},{"key":"materialzusammensetzung","type":"key_value","label":"Materialzusammensetzung","description":"Zum Beispiel Baumwolle 80 %, Polyester 20 %."},{"key":"passform","type":"select","label":"Passform","options":["Slim","Regular","Oversized","Loose"]},{"key":"zielgruppe","type":"select","label":"Zielgruppe","options":["Damen","Herren","Unisex","Kinder"]},{"key":"saison","type":"select","label":"Saison","options":["Ganzjährig","Frühjahr/Sommer","Herbst/Winter"]}]},{"key":"pflege","label":"Pflege & Herkunft","fields":[{"key":"pflegehinweise","type":"tags","label":"Pflegehinweise","description":"Zum Beispiel 30 Grad Wäsche, nicht bleichen."},{"key":"herkunft","type":"text","label":"Herkunftsland"},{"key":"groessentabelle","type":"key_value","label":"Größentabelle","description":"Größe und Maße, zum Beispiel M = Brust 102 cm."}]}]}'::jsonb,
   '{"axes":[{"key":"groesse","name":"Größe","display_type":"chips","presets":["XXS","XS","S","M","L","XL","XXL","3XL"],"allow_custom":true},{"key":"farbe","name":"Farbe","display_type":"color","presets":["Schwarz","Weiß","Grau","Beige","Navy","Rot","Grün"],"allow_custom":true}]}'::jsonb),
  ('lebensmittel','Lebensmittel','Produkte mit Inhalt, Zutaten, Allergenen und Nährwerten.','apple',1,true,
   '{"groups":[{"key":"inhalt","label":"Inhalt","fields":[{"key":"inhalt","type":"number","label":"Inhalt"},{"key":"einheit","type":"select","label":"Einheit","options":["g","kg","ml","l","Stück"]},{"key":"grundpreiseinheit","type":"select","label":"Grundpreiseinheit","options":["100 g","1 kg","100 ml","1 l","1 Stück"]}]},{"key":"zusammensetzung","label":"Zusammensetzung","fields":[{"key":"zutaten","type":"textarea","label":"Zutaten"},{"key":"allergene","type":"multiselect","label":"Allergene","options":["Gluten","Krebstiere","Eier","Fisch","Erdnüsse","Soja","Milch","Schalenfrüchte","Sellerie","Senf","Sesam","Schwefeldioxid","Lupinen","Weichtiere"]},{"key":"naehrwerte","type":"key_value","label":"Nährwerte je 100 g/ml","description":"Zum Beispiel Energie = 250 kcal."},{"key":"alkoholgehalt","type":"measurement","label":"Alkoholgehalt","unit":"% vol"}]},{"key":"herkunft","label":"Herkunft & Lagerung","fields":[{"key":"herkunft","type":"text","label":"Herkunft"},{"key":"hersteller","type":"text","label":"Hersteller"},{"key":"aufbewahrung","type":"textarea","label":"Aufbewahrung"},{"key":"mhd_relevant","type":"boolean","label":"Mindesthaltbarkeitsdatum relevant"},{"key":"pfand_relevant","type":"boolean","label":"Pfand relevant"},{"key":"hinweise","type":"textarea","label":"Weitere Hinweise"}]}]}'::jsonb,
   '{"axes":[{"key":"groesse","name":"Größe / Inhalt","display_type":"chips","presets":[],"allow_custom":true}]}'::jsonb),
  ('kosmetik','Kosmetik','Pflege- und Beautyprodukte mit INCI und Anwendungshinweisen.','sparkles',1,true,
   '{"groups":[{"key":"inhalt","label":"Inhalt","fields":[{"key":"inhalt","type":"number","label":"Inhalt"},{"key":"einheit","type":"select","label":"Einheit","options":["ml","l","g","kg","Stück"]},{"key":"grundpreiseinheit","type":"select","label":"Grundpreiseinheit","options":["100 ml","1 l","100 g","1 kg"]}]},{"key":"details","label":"Produktangaben","fields":[{"key":"inci","type":"textarea","label":"INCI"},{"key":"hauttyp","type":"multiselect","label":"Hauttyp","options":["Normal","Trocken","Fettig","Mischhaut","Empfindlich","Reife Haut"]},{"key":"anwendung","type":"textarea","label":"Anwendung"},{"key":"warnhinweise","type":"textarea","label":"Warnhinweise"},{"key":"duft","type":"text","label":"Duft"},{"key":"farbe","type":"color","label":"Farbe"},{"key":"hersteller","type":"text","label":"Hersteller"},{"key":"herkunft","type":"text","label":"Herkunft"}]}]}'::jsonb,
   '{"axes":[{"key":"groesse","name":"Größe","display_type":"chips","presets":[],"allow_custom":true},{"key":"farbe","name":"Farbton","display_type":"color","presets":[],"allow_custom":true}]}'::jsonb),
  ('elektronik','Elektronik','Geräte mit technischen Spezifikationen und Lieferumfang.','cpu',1,true,
   '{"groups":[{"key":"geraet","label":"Gerät","fields":[{"key":"hersteller","type":"text","label":"Hersteller"},{"key":"modell","type":"text","label":"Modell"},{"key":"ean","type":"text","label":"EAN"},{"key":"leistung","type":"measurement","label":"Leistung","unit":"W"},{"key":"gewicht","type":"measurement","label":"Gewicht","unit":"g"},{"key":"abmessungen","type":"key_value","label":"Abmessungen","description":"Breite, Höhe, Tiefe."}]},{"key":"technik","label":"Technische Daten","fields":[{"key":"spezifikationen","type":"key_value","label":"Technische Spezifikationen"},{"key":"lieferumfang","type":"tags","label":"Lieferumfang"},{"key":"garantie","type":"textarea","label":"Garantiehinweise"}]}]}'::jsonb,
   '{"axes":[{"key":"farbe","name":"Farbe","display_type":"color","presets":["Schwarz","Weiß","Silber","Space Grau"],"allow_custom":true},{"key":"speicher","name":"Speicher","display_type":"chips","presets":["64 GB","128 GB","256 GB","512 GB","1 TB"],"allow_custom":true}]}'::jsonb),
  ('moebel','Möbel','Möbelstücke mit Maßen, Material und Montagehinweisen.','sofa',1,true,
   '{"groups":[{"key":"masse","label":"Maße","fields":[{"key":"breite","type":"measurement","label":"Breite","unit":"cm"},{"key":"hoehe","type":"measurement","label":"Höhe","unit":"cm"},{"key":"tiefe","type":"measurement","label":"Tiefe","unit":"cm"},{"key":"gewicht","type":"measurement","label":"Gewicht","unit":"kg"}]},{"key":"details","label":"Ausführung","fields":[{"key":"material","type":"text","label":"Material"},{"key":"farbe","type":"color","label":"Farbe"},{"key":"stil","type":"select","label":"Stil","options":["Modern","Skandinavisch","Industrial","Klassisch","Landhaus"]},{"key":"montage","type":"boolean","label":"Montage erforderlich"},{"key":"lieferumfang","type":"tags","label":"Lieferumfang"},{"key":"pflegehinweise","type":"textarea","label":"Pflegehinweise"}]}]}'::jsonb,
   '{"axes":[{"key":"farbe","name":"Farbe","display_type":"color","presets":["Eiche","Nussbaum","Weiß","Schwarz","Grau"],"allow_custom":true},{"key":"groesse","name":"Größe","display_type":"chips","presets":[],"allow_custom":true}]}'::jsonb),
  ('schmuck','Schmuck','Schmuckstücke mit Material, Steinen und Größen.','gem',1,true,
   '{"groups":[{"key":"art","label":"Art","fields":[{"key":"schmucktyp","type":"select","label":"Schmucktyp","options":["Ring","Kette","Armband","Ohrring","Anhänger"]},{"key":"material","type":"text","label":"Material"},{"key":"legierung","type":"text","label":"Legierung"},{"key":"farbe","type":"color","label":"Farbe"},{"key":"stein","type":"text","label":"Stein"},{"key":"gewicht","type":"measurement","label":"Gewicht","unit":"g"}]},{"key":"masse","label":"Maße","fields":[{"key":"ringgroesse","type":"text","label":"Ringgröße","visible_if":{"field":"schmucktyp","equals":"Ring"}},{"key":"laenge","type":"measurement","label":"Länge","unit":"cm","visible_if":{"field":"schmucktyp","in":["Kette","Armband"]}},{"key":"pflegehinweise","type":"textarea","label":"Pflegehinweise"}]}]}'::jsonb,
   '{"axes":[{"key":"groesse","name":"Größe","display_type":"chips","presets":[],"allow_custom":true},{"key":"material","name":"Material","display_type":"chips","presets":["Silber 925","Gold 585","Edelstahl"],"allow_custom":true}]}'::jsonb),
  ('digital','Digitales Produkt','Downloads und Lizenzen ohne Versand.','download',1,true,
   '{"groups":[{"key":"datei","label":"Datei & Lizenz","fields":[{"key":"dateityp","type":"select","label":"Dateityp","options":["PDF","ZIP","MP3","MP4","EPUB","Sonstiges"]},{"key":"datei","type":"media","label":"Download-Datei"},{"key":"lizenztyp","type":"select","label":"Lizenztyp","options":["Einzellizenz","Mehrplatzlizenz","Kommerziell","Privat"]},{"key":"downloadlimit","type":"number","label":"Downloadlimit"},{"key":"ablaufzeit","type":"number","label":"Ablaufzeit in Tagen"}]}]}'::jsonb,
   '{"axes":[]}'::jsonb),
  ('dienstleistung','Dienstleistung','Leistungen mit Dauer und Durchführungsort.','handshake',1,true,
   '{"groups":[{"key":"leistung","label":"Leistung","fields":[{"key":"leistungsart","type":"text","label":"Leistungsart"},{"key":"dauer","type":"measurement","label":"Dauer","unit":"Minuten"},{"key":"leistungsbeschreibung","type":"textarea","label":"Leistungsbeschreibung"},{"key":"ort","type":"select","label":"Ort","options":["Vor Ort","Remote","Hybrid"]},{"key":"vorbereitung","type":"textarea","label":"Vorbereitungshinweise"}]}]}'::jsonb,
   '{"axes":[]}'::jsonb);
  END IF;
END
$eyis_seed$;
