-- EYIS Database Install Pack — Tabellen: documents (documents-tables-a)
-- Automatisch erzeugt. Nicht von Hand bearbeiten.

SET check_function_bodies = off;

CREATE TABLE public."credit_note_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "credit_note_id" uuid NOT NULL,
  "invoice_item_id" uuid,
  "position" integer NOT NULL,
  "item_type" invoice_item_type DEFAULT 'product'::invoice_item_type NOT NULL,
  "product_name" text NOT NULL,
  "variant_name" text,
  "sku" text,
  "description" text,
  "quantity" numeric(14,3) DEFAULT 1 NOT NULL,
  "unit" text DEFAULT 'C62'::text NOT NULL,
  "unit_net_minor" bigint DEFAULT 0 NOT NULL,
  "line_net_minor" bigint DEFAULT 0 NOT NULL,
  "tax_rate_basis_points" integer DEFAULT 0 NOT NULL,
  "tax_reason_code" text DEFAULT 'standard_rate'::text NOT NULL,
  "tax_minor" bigint DEFAULT 0 NOT NULL,
  "line_gross_minor" bigint DEFAULT 0 NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "credit_note_items_credit_note_id_position_key" UNIQUE (credit_note_id, "position"),
  CONSTRAINT "credit_note_items_pkey" PRIMARY KEY (id)
);

CREATE TABLE public."credit_notes" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "shop_id" uuid NOT NULL,
  "order_id" uuid NOT NULL,
  "invoice_id" uuid NOT NULL,
  "refund_id" uuid,
  "credit_note_number" text,
  "status" credit_note_status DEFAULT 'draft'::credit_note_status NOT NULL,
  "currency_code" text NOT NULL,
  "reason" text,
  "subtotal_net_minor" bigint DEFAULT 0 NOT NULL,
  "tax_total_minor" bigint DEFAULT 0 NOT NULL,
  "total_gross_minor" bigint DEFAULT 0 NOT NULL,
  "seller_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "customer_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "branding_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "tax_breakdown" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_by" uuid,
  "issued_by" uuid,
  "voided_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "issued_at" timestamp with time zone,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "credit_notes_organization_id_credit_note_number_key" UNIQUE (organization_id, credit_note_number),
  CONSTRAINT "credit_notes_pkey" PRIMARY KEY (id)
);

CREATE TABLE public."document_branding" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "shop_id" uuid NOT NULL,
  "preset" text DEFAULT 'clean'::text NOT NULL,
  "logo_media_id" uuid,
  "primary_color" text DEFAULT '#1F2937'::text NOT NULL,
  "secondary_color" text,
  "font_family" text DEFAULT 'helvetica'::text NOT NULL,
  "sender_block" text,
  "bank_details" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "payment_details" text,
  "footer_text" text,
  "legal_footer" text,
  "show_product_sku" boolean DEFAULT true NOT NULL,
  "show_product_images" boolean DEFAULT false NOT NULL,
  "show_tax_breakdown" boolean DEFAULT true NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "document_branding_pkey" PRIMARY KEY (id),
  CONSTRAINT "document_branding_shop_id_key" UNIQUE (shop_id)
);

CREATE TABLE public."document_files" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "shop_id" uuid NOT NULL,
  "document_type" document_type NOT NULL,
  "document_id" uuid NOT NULL,
  "format" document_format DEFAULT 'pdf'::document_format NOT NULL,
  "status" document_format_status DEFAULT 'generated'::document_format_status NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "renderer_version" text,
  "storage_path" text,
  "mime_type" text DEFAULT 'application/pdf'::text NOT NULL,
  "file_size" integer,
  "checksum" text,
  "validation_errors" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "document_files_document_id_format_version_key" UNIQUE (document_id, format, version),
  CONSTRAINT "document_files_pkey" PRIMARY KEY (id)
);

CREATE TABLE public."document_sequences" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "shop_id" uuid NOT NULL,
  "document_type" document_type NOT NULL,
  "prefix" text DEFAULT 'RE'::text NOT NULL,
  "suffix" text,
  "next_number" bigint DEFAULT 1 NOT NULL,
  "padding" integer DEFAULT 6 NOT NULL,
  "reset_policy" sequence_reset_policy DEFAULT 'yearly'::sequence_reset_policy NOT NULL,
  "current_period" text,
  "include_period" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "document_sequences_pkey" PRIMARY KEY (id),
  CONSTRAINT "document_sequences_shop_id_document_type_key" UNIQUE (shop_id, document_type)
);

CREATE TABLE public."invoice_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "invoice_id" uuid NOT NULL,
  "order_item_id" uuid,
  "position" integer NOT NULL,
  "item_type" invoice_item_type DEFAULT 'product'::invoice_item_type NOT NULL,
  "product_name" text NOT NULL,
  "variant_name" text,
  "sku" text,
  "description" text,
  "quantity" numeric(14,3) DEFAULT 1 NOT NULL,
  "unit" text DEFAULT 'C62'::text NOT NULL,
  "unit_net_minor" bigint DEFAULT 0 NOT NULL,
  "discount_minor" bigint DEFAULT 0 NOT NULL,
  "line_net_minor" bigint DEFAULT 0 NOT NULL,
  "tax_rate_basis_points" integer DEFAULT 0 NOT NULL,
  "tax_reason_code" text DEFAULT 'standard_rate'::text NOT NULL,
  "tax_minor" bigint DEFAULT 0 NOT NULL,
  "line_gross_minor" bigint DEFAULT 0 NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "invoice_items_invoice_id_position_key" UNIQUE (invoice_id, "position"),
  CONSTRAINT "invoice_items_pkey" PRIMARY KEY (id)
);

CREATE TABLE public."invoice_settings" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "shop_id" uuid NOT NULL,
  "company_name" text,
  "legal_form" text,
  "address_line1" text,
  "address_line2" text,
  "postal_code" text,
  "city" text,
  "country_code" text DEFAULT 'DE'::text NOT NULL,
  "tax_number" text,
  "vat_id" text,
  "register_court" text,
  "register_number" text,
  "managing_director" text,
  "contact_email" text,
  "contact_phone" text,
  "website" text,
  "bank_account_holder" text,
  "bank_iban" text,
  "bank_bic" text,
  "bank_name" text,
  "payment_terms_days" integer DEFAULT 14 NOT NULL,
  "payment_terms_text" text,
  "invoice_creation_strategy" invoice_creation_strategy DEFAULT 'on_order_paid'::invoice_creation_strategy NOT NULL,
  "automatically_create_invoice" boolean DEFAULT false NOT NULL,
  "automatically_issue_invoice" boolean DEFAULT false NOT NULL,
  "credit_note_draft_on_refund" boolean DEFAULT false NOT NULL,
  "einvoice_zugferd_enabled" boolean DEFAULT false NOT NULL,
  "einvoice_xrechnung_enabled" boolean DEFAULT false NOT NULL,
  "leitweg_id" text,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "invoice_settings_pkey" PRIMARY KEY (id),
  CONSTRAINT "invoice_settings_shop_id_key" UNIQUE (shop_id)
);

CREATE TABLE public."invoices" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "shop_id" uuid NOT NULL,
  "order_id" uuid NOT NULL,
  "invoice_number" text,
  "status" invoice_status DEFAULT 'draft'::invoice_status NOT NULL,
  "currency_code" text NOT NULL,
  "issue_date" date,
  "service_date" date,
  "due_date" date,
  "customer_type" tax_customer_type DEFAULT 'consumer'::tax_customer_type NOT NULL,
  "customer_email" text,
  "customer_name" text,
  "customer_company" text,
  "customer_vat_id" text,
  "billing_address_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "seller_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "branding_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "payment_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "subtotal_net_minor" bigint DEFAULT 0 NOT NULL,
  "discount_minor" bigint DEFAULT 0 NOT NULL,
  "shipping_net_minor" bigint DEFAULT 0 NOT NULL,
  "tax_total_minor" bigint DEFAULT 0 NOT NULL,
  "total_gross_minor" bigint DEFAULT 0 NOT NULL,
  "paid_minor" bigint DEFAULT 0 NOT NULL,
  "credited_minor" bigint DEFAULT 0 NOT NULL,
  "tax_breakdown" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "tax_engine_version" text,
  "source_order_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "buyer_reference" text,
  "purchase_order_reference" text,
  "contract_reference" text,
  "payment_terms" text,
  "notes" text,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_by" uuid,
  "issued_by" uuid,
  "voided_at" timestamp with time zone,
  "void_reason" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "issued_at" timestamp with time zone,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "invoices_organization_id_invoice_number_key" UNIQUE (organization_id, invoice_number),
  CONSTRAINT "invoices_pkey" PRIMARY KEY (id)
);
