/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app/audit'
import { Route as AuthenticatedAppKategorienRouteImport } from './routes/_authenticated/app/kategorien'
import { Route as AuthenticatedAppMedienRouteImport } from './routes/_authenticated/app/medien'
import { Route as AuthenticatedAppShopsRouteImport } from './routes/_authenticated/app/shops'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app/team'
import { Route as AuthenticatedAppLagerIndexRouteImport } from './routes/_authenticated/app/lager/index'
import { Route as AuthenticatedAppLagerWareneingangRouteImport } from './routes/_authenticated/app/lager/wareneingang'
import { Route as AuthenticatedAppMarketingPromotionsRouteImport } from './routes/_authenticated/app/marketing/promotions'
import { Route as AuthenticatedAppPreiseIndexRouteImport } from './routes/_authenticated/app/preise/index'
import { Route as AuthenticatedAppPreiseTestenRouteImport } from './routes/_authenticated/app/preise/testen'
import { Route as AuthenticatedAppProdukteIndexRouteImport } from './routes/_authenticated/app/produkte/index'
import { Route as AuthenticatedAppProdukteProductIdRouteImport } from './routes/_authenticated/app/produkte/$productId'
import { Route as AuthenticatedAppProdukteNeuRouteImport } from './routes/_authenticated/app/produkte/neu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppKategorienRoute =
  AuthenticatedAppKategorienRouteImport.update({
    id: '/app/kategorien',
    path: '/app/kategorien',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMedienRoute = AuthenticatedAppMedienRouteImport.update({
  id: '/app/medien',
  path: '/app/medien',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppShopsRoute = AuthenticatedAppShopsRouteImport.update({
  id: '/app/shops',
  path: '/app/shops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppLagerIndexRoute =
  AuthenticatedAppLagerIndexRouteImport.update({
    id: '/app/lager/',
    path: '/app/lager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerWareneingangRoute =
  AuthenticatedAppLagerWareneingangRouteImport.update({
    id: '/app/lager/wareneingang',
    path: '/app/lager/wareneingang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMarketingPromotionsRoute =
  AuthenticatedAppMarketingPromotionsRouteImport.update({
    id: '/app/marketing/promotions',
    path: '/app/marketing/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPreiseIndexRoute =
  AuthenticatedAppPreiseIndexRouteImport.update({
    id: '/app/preise/',
    path: '/app/preise/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPreiseTestenRoute =
  AuthenticatedAppPreiseTestenRouteImport.update({
    id: '/app/preise/testen',
    path: '/app/preise/testen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteIndexRoute =
  AuthenticatedAppProdukteIndexRouteImport.update({
    id: '/app/produkte/',
    path: '/app/produkte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteProductIdRoute =
  AuthenticatedAppProdukteProductIdRouteImport.update({
    id: '/app/produkte/$productId',
    path: '/app/produkte/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteNeuRoute =
  AuthenticatedAppProdukteNeuRouteImport.update({
    id: '/app/produkte/neu',
    path: '/app/produkte/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/app/medien': typeof AuthenticatedAppMedienRoute
  '/app/shops': typeof AuthenticatedAppShopsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/app/lager/': typeof AuthenticatedAppLagerIndexRoute
  '/app/preise/': typeof AuthenticatedAppPreiseIndexRoute
  '/app/produkte/': typeof AuthenticatedAppProdukteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/app/medien': typeof AuthenticatedAppMedienRoute
  '/app/shops': typeof AuthenticatedAppShopsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/app/lager': typeof AuthenticatedAppLagerIndexRoute
  '/app/preise': typeof AuthenticatedAppPreiseIndexRoute
  '/app/produkte': typeof AuthenticatedAppProdukteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/_authenticated/app/medien': typeof AuthenticatedAppMedienRoute
  '/_authenticated/app/shops': typeof AuthenticatedAppShopsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/_authenticated/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/_authenticated/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/_authenticated/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/_authenticated/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/_authenticated/app/lager/': typeof AuthenticatedAppLagerIndexRoute
  '/_authenticated/app/preise/': typeof AuthenticatedAppPreiseIndexRoute
  '/_authenticated/app/produkte/': typeof AuthenticatedAppProdukteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite'
    | '/app/audit'
    | '/app/kategorien'
    | '/app/medien'
    | '/app/shops'
    | '/app/team'
    | '/app/'
    | '/app/lager/wareneingang'
    | '/app/marketing/promotions'
    | '/app/preise/testen'
    | '/app/produkte/$productId'
    | '/app/produkte/neu'
    | '/app/lager/'
    | '/app/preise/'
    | '/app/produkte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/app/audit'
    | '/app/kategorien'
    | '/app/medien'
    | '/app/shops'
    | '/app/team'
    | '/app'
    | '/app/lager/wareneingang'
    | '/app/marketing/promotions'
    | '/app/preise/testen'
    | '/app/produkte/$productId'
    | '/app/produkte/neu'
    | '/app/lager'
    | '/app/preise'
    | '/app/produkte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/invite'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/kategorien'
    | '/_authenticated/app/medien'
    | '/_authenticated/app/shops'
    | '/_authenticated/app/team'
    | '/_authenticated/app/'
    | '/_authenticated/app/lager/wareneingang'
    | '/_authenticated/app/marketing/promotions'
    | '/_authenticated/app/preise/testen'
    | '/_authenticated/app/produkte/$productId'
    | '/_authenticated/app/produkte/neu'
    | '/_authenticated/app/lager/'
    | '/_authenticated/app/preise/'
    | '/_authenticated/app/produkte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteRoute: typeof InviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kategorien': {
      id: '/_authenticated/app/kategorien'
      path: '/app/kategorien'
      fullPath: '/app/kategorien'
      preLoaderRoute: typeof AuthenticatedAppKategorienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/medien': {
      id: '/_authenticated/app/medien'
      path: '/app/medien'
      fullPath: '/app/medien'
      preLoaderRoute: typeof AuthenticatedAppMedienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/shops': {
      id: '/_authenticated/app/shops'
      path: '/app/shops'
      fullPath: '/app/shops'
      preLoaderRoute: typeof AuthenticatedAppShopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/': {
      id: '/_authenticated/app/lager/'
      path: '/app/lager'
      fullPath: '/app/lager/'
      preLoaderRoute: typeof AuthenticatedAppLagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/wareneingang': {
      id: '/_authenticated/app/lager/wareneingang'
      path: '/app/lager/wareneingang'
      fullPath: '/app/lager/wareneingang'
      preLoaderRoute: typeof AuthenticatedAppLagerWareneingangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/marketing/promotions': {
      id: '/_authenticated/app/marketing/promotions'
      path: '/app/marketing/promotions'
      fullPath: '/app/marketing/promotions'
      preLoaderRoute: typeof AuthenticatedAppMarketingPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/preise/': {
      id: '/_authenticated/app/preise/'
      path: '/app/preise'
      fullPath: '/app/preise/'
      preLoaderRoute: typeof AuthenticatedAppPreiseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/preise/testen': {
      id: '/_authenticated/app/preise/testen'
      path: '/app/preise/testen'
      fullPath: '/app/preise/testen'
      preLoaderRoute: typeof AuthenticatedAppPreiseTestenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/': {
      id: '/_authenticated/app/produkte/'
      path: '/app/produkte'
      fullPath: '/app/produkte/'
      preLoaderRoute: typeof AuthenticatedAppProdukteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/$productId': {
      id: '/_authenticated/app/produkte/$productId'
      path: '/app/produkte/$productId'
      fullPath: '/app/produkte/$productId'
      preLoaderRoute: typeof AuthenticatedAppProdukteProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/neu': {
      id: '/_authenticated/app/produkte/neu'
      path: '/app/produkte/neu'
      fullPath: '/app/produkte/neu'
      preLoaderRoute: typeof AuthenticatedAppProdukteNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppKategorienRoute: typeof AuthenticatedAppKategorienRoute
  AuthenticatedAppMedienRoute: typeof AuthenticatedAppMedienRoute
  AuthenticatedAppShopsRoute: typeof AuthenticatedAppShopsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppLagerWareneingangRoute: typeof AuthenticatedAppLagerWareneingangRoute
  AuthenticatedAppMarketingPromotionsRoute: typeof AuthenticatedAppMarketingPromotionsRoute
  AuthenticatedAppPreiseTestenRoute: typeof AuthenticatedAppPreiseTestenRoute
  AuthenticatedAppProdukteProductIdRoute: typeof AuthenticatedAppProdukteProductIdRoute
  AuthenticatedAppProdukteNeuRoute: typeof AuthenticatedAppProdukteNeuRoute
  AuthenticatedAppLagerIndexRoute: typeof AuthenticatedAppLagerIndexRoute
  AuthenticatedAppPreiseIndexRoute: typeof AuthenticatedAppPreiseIndexRoute
  AuthenticatedAppProdukteIndexRoute: typeof AuthenticatedAppProdukteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppKategorienRoute: AuthenticatedAppKategorienRoute,
  AuthenticatedAppMedienRoute: AuthenticatedAppMedienRoute,
  AuthenticatedAppShopsRoute: AuthenticatedAppShopsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppLagerWareneingangRoute:
    AuthenticatedAppLagerWareneingangRoute,
  AuthenticatedAppMarketingPromotionsRoute:
    AuthenticatedAppMarketingPromotionsRoute,
  AuthenticatedAppPreiseTestenRoute: AuthenticatedAppPreiseTestenRoute,
  AuthenticatedAppProdukteProductIdRoute:
    AuthenticatedAppProdukteProductIdRoute,
  AuthenticatedAppProdukteNeuRoute: AuthenticatedAppProdukteNeuRoute,
  AuthenticatedAppLagerIndexRoute: AuthenticatedAppLagerIndexRoute,
  AuthenticatedAppPreiseIndexRoute: AuthenticatedAppPreiseIndexRoute,
  AuthenticatedAppProdukteIndexRoute: AuthenticatedAppProdukteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteRoute: InviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
