/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app/audit'
import { Route as AuthenticatedAppKategorienRouteImport } from './routes/_authenticated/app/kategorien'
import { Route as AuthenticatedAppMedienRouteImport } from './routes/_authenticated/app/medien'
import { Route as AuthenticatedAppShopsRouteImport } from './routes/_authenticated/app/shops'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app/team'
import { Route as AuthenticatedAppVersandRouteImport } from './routes/_authenticated/app/versand'
import { Route as AuthenticatedAppWarenkoerbeRouteImport } from './routes/_authenticated/app/warenkoerbe'
import { Route as AuthenticatedAppZahlungenRouteImport } from './routes/_authenticated/app/zahlungen'
import { Route as AuthenticatedAppBestellungenIndexRouteImport } from './routes/_authenticated/app/bestellungen/index'
import { Route as AuthenticatedAppBestellungenOrderIdRouteImport } from './routes/_authenticated/app/bestellungen/$orderId'
import { Route as AuthenticatedAppLagerIndexRouteImport } from './routes/_authenticated/app/lager/index'
import { Route as AuthenticatedAppLagerBewegungenRouteImport } from './routes/_authenticated/app/lager/bewegungen'
import { Route as AuthenticatedAppLagerLagerorteRouteImport } from './routes/_authenticated/app/lager/lagerorte'
import { Route as AuthenticatedAppLagerReservierungenRouteImport } from './routes/_authenticated/app/lager/reservierungen'
import { Route as AuthenticatedAppLagerTransfersRouteImport } from './routes/_authenticated/app/lager/transfers'
import { Route as AuthenticatedAppLagerWareneingangRouteImport } from './routes/_authenticated/app/lager/wareneingang'
import { Route as AuthenticatedAppMarketingPromotionsRouteImport } from './routes/_authenticated/app/marketing/promotions'
import { Route as AuthenticatedAppPreiseIndexRouteImport } from './routes/_authenticated/app/preise/index'
import { Route as AuthenticatedAppPreiseTestenRouteImport } from './routes/_authenticated/app/preise/testen'
import { Route as AuthenticatedAppProdukteIndexRouteImport } from './routes/_authenticated/app/produkte/index'
import { Route as AuthenticatedAppProdukteProductIdRouteImport } from './routes/_authenticated/app/produkte/$productId'
import { Route as AuthenticatedAppProdukteNeuRouteImport } from './routes/_authenticated/app/produkte/neu'
import { Route as AuthenticatedAppSystemStorefrontTestRouteImport } from './routes/_authenticated/app/system/storefront-test'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppKategorienRoute =
  AuthenticatedAppKategorienRouteImport.update({
    id: '/app/kategorien',
    path: '/app/kategorien',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMedienRoute = AuthenticatedAppMedienRouteImport.update({
  id: '/app/medien',
  path: '/app/medien',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppShopsRoute = AuthenticatedAppShopsRouteImport.update({
  id: '/app/shops',
  path: '/app/shops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVersandRoute = AuthenticatedAppVersandRouteImport.update({
  id: '/app/versand',
  path: '/app/versand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppWarenkoerbeRoute =
  AuthenticatedAppWarenkoerbeRouteImport.update({
    id: '/app/warenkoerbe',
    path: '/app/warenkoerbe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppZahlungenRoute =
  AuthenticatedAppZahlungenRouteImport.update({
    id: '/app/zahlungen',
    path: '/app/zahlungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBestellungenIndexRoute =
  AuthenticatedAppBestellungenIndexRouteImport.update({
    id: '/app/bestellungen/',
    path: '/app/bestellungen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBestellungenOrderIdRoute =
  AuthenticatedAppBestellungenOrderIdRouteImport.update({
    id: '/app/bestellungen/$orderId',
    path: '/app/bestellungen/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerIndexRoute =
  AuthenticatedAppLagerIndexRouteImport.update({
    id: '/app/lager/',
    path: '/app/lager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerBewegungenRoute =
  AuthenticatedAppLagerBewegungenRouteImport.update({
    id: '/app/lager/bewegungen',
    path: '/app/lager/bewegungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerLagerorteRoute =
  AuthenticatedAppLagerLagerorteRouteImport.update({
    id: '/app/lager/lagerorte',
    path: '/app/lager/lagerorte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerReservierungenRoute =
  AuthenticatedAppLagerReservierungenRouteImport.update({
    id: '/app/lager/reservierungen',
    path: '/app/lager/reservierungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerTransfersRoute =
  AuthenticatedAppLagerTransfersRouteImport.update({
    id: '/app/lager/transfers',
    path: '/app/lager/transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerWareneingangRoute =
  AuthenticatedAppLagerWareneingangRouteImport.update({
    id: '/app/lager/wareneingang',
    path: '/app/lager/wareneingang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMarketingPromotionsRoute =
  AuthenticatedAppMarketingPromotionsRouteImport.update({
    id: '/app/marketing/promotions',
    path: '/app/marketing/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPreiseIndexRoute =
  AuthenticatedAppPreiseIndexRouteImport.update({
    id: '/app/preise/',
    path: '/app/preise/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPreiseTestenRoute =
  AuthenticatedAppPreiseTestenRouteImport.update({
    id: '/app/preise/testen',
    path: '/app/preise/testen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteIndexRoute =
  AuthenticatedAppProdukteIndexRouteImport.update({
    id: '/app/produkte/',
    path: '/app/produkte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteProductIdRoute =
  AuthenticatedAppProdukteProductIdRouteImport.update({
    id: '/app/produkte/$productId',
    path: '/app/produkte/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteNeuRoute =
  AuthenticatedAppProdukteNeuRouteImport.update({
    id: '/app/produkte/neu',
    path: '/app/produkte/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSystemStorefrontTestRoute =
  AuthenticatedAppSystemStorefrontTestRouteImport.update({
    id: '/app/system/storefront-test',
    path: '/app/system/storefront-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/app/medien': typeof AuthenticatedAppMedienRoute
  '/app/shops': typeof AuthenticatedAppShopsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/versand': typeof AuthenticatedAppVersandRoute
  '/app/warenkoerbe': typeof AuthenticatedAppWarenkoerbeRoute
  '/app/zahlungen': typeof AuthenticatedAppZahlungenRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/bestellungen/$orderId': typeof AuthenticatedAppBestellungenOrderIdRoute
  '/app/lager/bewegungen': typeof AuthenticatedAppLagerBewegungenRoute
  '/app/lager/lagerorte': typeof AuthenticatedAppLagerLagerorteRoute
  '/app/lager/reservierungen': typeof AuthenticatedAppLagerReservierungenRoute
  '/app/lager/transfers': typeof AuthenticatedAppLagerTransfersRoute
  '/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/app/system/storefront-test': typeof AuthenticatedAppSystemStorefrontTestRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/bestellungen/': typeof AuthenticatedAppBestellungenIndexRoute
  '/app/lager/': typeof AuthenticatedAppLagerIndexRoute
  '/app/preise/': typeof AuthenticatedAppPreiseIndexRoute
  '/app/produkte/': typeof AuthenticatedAppProdukteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/app/medien': typeof AuthenticatedAppMedienRoute
  '/app/shops': typeof AuthenticatedAppShopsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/versand': typeof AuthenticatedAppVersandRoute
  '/app/warenkoerbe': typeof AuthenticatedAppWarenkoerbeRoute
  '/app/zahlungen': typeof AuthenticatedAppZahlungenRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/bestellungen/$orderId': typeof AuthenticatedAppBestellungenOrderIdRoute
  '/app/lager/bewegungen': typeof AuthenticatedAppLagerBewegungenRoute
  '/app/lager/lagerorte': typeof AuthenticatedAppLagerLagerorteRoute
  '/app/lager/reservierungen': typeof AuthenticatedAppLagerReservierungenRoute
  '/app/lager/transfers': typeof AuthenticatedAppLagerTransfersRoute
  '/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/app/system/storefront-test': typeof AuthenticatedAppSystemStorefrontTestRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/bestellungen': typeof AuthenticatedAppBestellungenIndexRoute
  '/app/lager': typeof AuthenticatedAppLagerIndexRoute
  '/app/preise': typeof AuthenticatedAppPreiseIndexRoute
  '/app/produkte': typeof AuthenticatedAppProdukteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/_authenticated/app/medien': typeof AuthenticatedAppMedienRoute
  '/_authenticated/app/shops': typeof AuthenticatedAppShopsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/versand': typeof AuthenticatedAppVersandRoute
  '/_authenticated/app/warenkoerbe': typeof AuthenticatedAppWarenkoerbeRoute
  '/_authenticated/app/zahlungen': typeof AuthenticatedAppZahlungenRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/bestellungen/$orderId': typeof AuthenticatedAppBestellungenOrderIdRoute
  '/_authenticated/app/lager/bewegungen': typeof AuthenticatedAppLagerBewegungenRoute
  '/_authenticated/app/lager/lagerorte': typeof AuthenticatedAppLagerLagerorteRoute
  '/_authenticated/app/lager/reservierungen': typeof AuthenticatedAppLagerReservierungenRoute
  '/_authenticated/app/lager/transfers': typeof AuthenticatedAppLagerTransfersRoute
  '/_authenticated/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/_authenticated/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/_authenticated/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/_authenticated/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/_authenticated/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/_authenticated/app/system/storefront-test': typeof AuthenticatedAppSystemStorefrontTestRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/_authenticated/app/bestellungen/': typeof AuthenticatedAppBestellungenIndexRoute
  '/_authenticated/app/lager/': typeof AuthenticatedAppLagerIndexRoute
  '/_authenticated/app/preise/': typeof AuthenticatedAppPreiseIndexRoute
  '/_authenticated/app/produkte/': typeof AuthenticatedAppProdukteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite'
    | '/app/audit'
    | '/app/kategorien'
    | '/app/medien'
    | '/app/shops'
    | '/app/team'
    | '/app/versand'
    | '/app/warenkoerbe'
    | '/app/zahlungen'
    | '/app/'
    | '/app/bestellungen/$orderId'
    | '/app/lager/bewegungen'
    | '/app/lager/lagerorte'
    | '/app/lager/reservierungen'
    | '/app/lager/transfers'
    | '/app/lager/wareneingang'
    | '/app/marketing/promotions'
    | '/app/preise/testen'
    | '/app/produkte/$productId'
    | '/app/produkte/neu'
    | '/app/system/storefront-test'
    | '/api/public/webhooks/stripe'
    | '/app/bestellungen/'
    | '/app/lager/'
    | '/app/preise/'
    | '/app/produkte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/app/audit'
    | '/app/kategorien'
    | '/app/medien'
    | '/app/shops'
    | '/app/team'
    | '/app/versand'
    | '/app/warenkoerbe'
    | '/app/zahlungen'
    | '/app'
    | '/app/bestellungen/$orderId'
    | '/app/lager/bewegungen'
    | '/app/lager/lagerorte'
    | '/app/lager/reservierungen'
    | '/app/lager/transfers'
    | '/app/lager/wareneingang'
    | '/app/marketing/promotions'
    | '/app/preise/testen'
    | '/app/produkte/$productId'
    | '/app/produkte/neu'
    | '/app/system/storefront-test'
    | '/api/public/webhooks/stripe'
    | '/app/bestellungen'
    | '/app/lager'
    | '/app/preise'
    | '/app/produkte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/invite'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/kategorien'
    | '/_authenticated/app/medien'
    | '/_authenticated/app/shops'
    | '/_authenticated/app/team'
    | '/_authenticated/app/versand'
    | '/_authenticated/app/warenkoerbe'
    | '/_authenticated/app/zahlungen'
    | '/_authenticated/app/'
    | '/_authenticated/app/bestellungen/$orderId'
    | '/_authenticated/app/lager/bewegungen'
    | '/_authenticated/app/lager/lagerorte'
    | '/_authenticated/app/lager/reservierungen'
    | '/_authenticated/app/lager/transfers'
    | '/_authenticated/app/lager/wareneingang'
    | '/_authenticated/app/marketing/promotions'
    | '/_authenticated/app/preise/testen'
    | '/_authenticated/app/produkte/$productId'
    | '/_authenticated/app/produkte/neu'
    | '/_authenticated/app/system/storefront-test'
    | '/api/public/webhooks/stripe'
    | '/_authenticated/app/bestellungen/'
    | '/_authenticated/app/lager/'
    | '/_authenticated/app/preise/'
    | '/_authenticated/app/produkte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteRoute: typeof InviteRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kategorien': {
      id: '/_authenticated/app/kategorien'
      path: '/app/kategorien'
      fullPath: '/app/kategorien'
      preLoaderRoute: typeof AuthenticatedAppKategorienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/medien': {
      id: '/_authenticated/app/medien'
      path: '/app/medien'
      fullPath: '/app/medien'
      preLoaderRoute: typeof AuthenticatedAppMedienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/shops': {
      id: '/_authenticated/app/shops'
      path: '/app/shops'
      fullPath: '/app/shops'
      preLoaderRoute: typeof AuthenticatedAppShopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/versand': {
      id: '/_authenticated/app/versand'
      path: '/app/versand'
      fullPath: '/app/versand'
      preLoaderRoute: typeof AuthenticatedAppVersandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/warenkoerbe': {
      id: '/_authenticated/app/warenkoerbe'
      path: '/app/warenkoerbe'
      fullPath: '/app/warenkoerbe'
      preLoaderRoute: typeof AuthenticatedAppWarenkoerbeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/zahlungen': {
      id: '/_authenticated/app/zahlungen'
      path: '/app/zahlungen'
      fullPath: '/app/zahlungen'
      preLoaderRoute: typeof AuthenticatedAppZahlungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bestellungen/': {
      id: '/_authenticated/app/bestellungen/'
      path: '/app/bestellungen'
      fullPath: '/app/bestellungen/'
      preLoaderRoute: typeof AuthenticatedAppBestellungenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bestellungen/$orderId': {
      id: '/_authenticated/app/bestellungen/$orderId'
      path: '/app/bestellungen/$orderId'
      fullPath: '/app/bestellungen/$orderId'
      preLoaderRoute: typeof AuthenticatedAppBestellungenOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/': {
      id: '/_authenticated/app/lager/'
      path: '/app/lager'
      fullPath: '/app/lager/'
      preLoaderRoute: typeof AuthenticatedAppLagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/bewegungen': {
      id: '/_authenticated/app/lager/bewegungen'
      path: '/app/lager/bewegungen'
      fullPath: '/app/lager/bewegungen'
      preLoaderRoute: typeof AuthenticatedAppLagerBewegungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/lagerorte': {
      id: '/_authenticated/app/lager/lagerorte'
      path: '/app/lager/lagerorte'
      fullPath: '/app/lager/lagerorte'
      preLoaderRoute: typeof AuthenticatedAppLagerLagerorteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/reservierungen': {
      id: '/_authenticated/app/lager/reservierungen'
      path: '/app/lager/reservierungen'
      fullPath: '/app/lager/reservierungen'
      preLoaderRoute: typeof AuthenticatedAppLagerReservierungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/transfers': {
      id: '/_authenticated/app/lager/transfers'
      path: '/app/lager/transfers'
      fullPath: '/app/lager/transfers'
      preLoaderRoute: typeof AuthenticatedAppLagerTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/wareneingang': {
      id: '/_authenticated/app/lager/wareneingang'
      path: '/app/lager/wareneingang'
      fullPath: '/app/lager/wareneingang'
      preLoaderRoute: typeof AuthenticatedAppLagerWareneingangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/marketing/promotions': {
      id: '/_authenticated/app/marketing/promotions'
      path: '/app/marketing/promotions'
      fullPath: '/app/marketing/promotions'
      preLoaderRoute: typeof AuthenticatedAppMarketingPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/preise/': {
      id: '/_authenticated/app/preise/'
      path: '/app/preise'
      fullPath: '/app/preise/'
      preLoaderRoute: typeof AuthenticatedAppPreiseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/preise/testen': {
      id: '/_authenticated/app/preise/testen'
      path: '/app/preise/testen'
      fullPath: '/app/preise/testen'
      preLoaderRoute: typeof AuthenticatedAppPreiseTestenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/': {
      id: '/_authenticated/app/produkte/'
      path: '/app/produkte'
      fullPath: '/app/produkte/'
      preLoaderRoute: typeof AuthenticatedAppProdukteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/$productId': {
      id: '/_authenticated/app/produkte/$productId'
      path: '/app/produkte/$productId'
      fullPath: '/app/produkte/$productId'
      preLoaderRoute: typeof AuthenticatedAppProdukteProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/neu': {
      id: '/_authenticated/app/produkte/neu'
      path: '/app/produkte/neu'
      fullPath: '/app/produkte/neu'
      preLoaderRoute: typeof AuthenticatedAppProdukteNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/system/storefront-test': {
      id: '/_authenticated/app/system/storefront-test'
      path: '/app/system/storefront-test'
      fullPath: '/app/system/storefront-test'
      preLoaderRoute: typeof AuthenticatedAppSystemStorefrontTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppKategorienRoute: typeof AuthenticatedAppKategorienRoute
  AuthenticatedAppMedienRoute: typeof AuthenticatedAppMedienRoute
  AuthenticatedAppShopsRoute: typeof AuthenticatedAppShopsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppVersandRoute: typeof AuthenticatedAppVersandRoute
  AuthenticatedAppWarenkoerbeRoute: typeof AuthenticatedAppWarenkoerbeRoute
  AuthenticatedAppZahlungenRoute: typeof AuthenticatedAppZahlungenRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBestellungenOrderIdRoute: typeof AuthenticatedAppBestellungenOrderIdRoute
  AuthenticatedAppLagerBewegungenRoute: typeof AuthenticatedAppLagerBewegungenRoute
  AuthenticatedAppLagerLagerorteRoute: typeof AuthenticatedAppLagerLagerorteRoute
  AuthenticatedAppLagerReservierungenRoute: typeof AuthenticatedAppLagerReservierungenRoute
  AuthenticatedAppLagerTransfersRoute: typeof AuthenticatedAppLagerTransfersRoute
  AuthenticatedAppLagerWareneingangRoute: typeof AuthenticatedAppLagerWareneingangRoute
  AuthenticatedAppMarketingPromotionsRoute: typeof AuthenticatedAppMarketingPromotionsRoute
  AuthenticatedAppPreiseTestenRoute: typeof AuthenticatedAppPreiseTestenRoute
  AuthenticatedAppProdukteProductIdRoute: typeof AuthenticatedAppProdukteProductIdRoute
  AuthenticatedAppProdukteNeuRoute: typeof AuthenticatedAppProdukteNeuRoute
  AuthenticatedAppSystemStorefrontTestRoute: typeof AuthenticatedAppSystemStorefrontTestRoute
  AuthenticatedAppBestellungenIndexRoute: typeof AuthenticatedAppBestellungenIndexRoute
  AuthenticatedAppLagerIndexRoute: typeof AuthenticatedAppLagerIndexRoute
  AuthenticatedAppPreiseIndexRoute: typeof AuthenticatedAppPreiseIndexRoute
  AuthenticatedAppProdukteIndexRoute: typeof AuthenticatedAppProdukteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppKategorienRoute: AuthenticatedAppKategorienRoute,
  AuthenticatedAppMedienRoute: AuthenticatedAppMedienRoute,
  AuthenticatedAppShopsRoute: AuthenticatedAppShopsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppVersandRoute: AuthenticatedAppVersandRoute,
  AuthenticatedAppWarenkoerbeRoute: AuthenticatedAppWarenkoerbeRoute,
  AuthenticatedAppZahlungenRoute: AuthenticatedAppZahlungenRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBestellungenOrderIdRoute:
    AuthenticatedAppBestellungenOrderIdRoute,
  AuthenticatedAppLagerBewegungenRoute: AuthenticatedAppLagerBewegungenRoute,
  AuthenticatedAppLagerLagerorteRoute: AuthenticatedAppLagerLagerorteRoute,
  AuthenticatedAppLagerReservierungenRoute:
    AuthenticatedAppLagerReservierungenRoute,
  AuthenticatedAppLagerTransfersRoute: AuthenticatedAppLagerTransfersRoute,
  AuthenticatedAppLagerWareneingangRoute:
    AuthenticatedAppLagerWareneingangRoute,
  AuthenticatedAppMarketingPromotionsRoute:
    AuthenticatedAppMarketingPromotionsRoute,
  AuthenticatedAppPreiseTestenRoute: AuthenticatedAppPreiseTestenRoute,
  AuthenticatedAppProdukteProductIdRoute:
    AuthenticatedAppProdukteProductIdRoute,
  AuthenticatedAppProdukteNeuRoute: AuthenticatedAppProdukteNeuRoute,
  AuthenticatedAppSystemStorefrontTestRoute:
    AuthenticatedAppSystemStorefrontTestRoute,
  AuthenticatedAppBestellungenIndexRoute:
    AuthenticatedAppBestellungenIndexRoute,
  AuthenticatedAppLagerIndexRoute: AuthenticatedAppLagerIndexRoute,
  AuthenticatedAppPreiseIndexRoute: AuthenticatedAppPreiseIndexRoute,
  AuthenticatedAppProdukteIndexRoute: AuthenticatedAppProdukteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteRoute: InviteRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
