/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalGastRouteImport } from './routes/portal/gast'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app/audit'
import { Route as AuthenticatedAppKategorienRouteImport } from './routes/_authenticated/app/kategorien'
import { Route as AuthenticatedAppMedienRouteImport } from './routes/_authenticated/app/medien'
import { Route as AuthenticatedAppShopsRouteImport } from './routes/_authenticated/app/shops'
import { Route as AuthenticatedAppSteuernRouteImport } from './routes/_authenticated/app/steuern'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app/team'
import { Route as AuthenticatedAppWarenkoerbeRouteImport } from './routes/_authenticated/app/warenkoerbe'
import { Route as AuthenticatedAppZahlungenRouteImport } from './routes/_authenticated/app/zahlungen'
import { Route as PortalBestellungenOrderIdRouteImport } from './routes/portal/bestellungen/$orderId'
import { Route as AuthenticatedAppBestellungenIndexRouteImport } from './routes/_authenticated/app/bestellungen/index'
import { Route as AuthenticatedAppBestellungenOrderIdRouteImport } from './routes/_authenticated/app/bestellungen/$orderId'
import { Route as AuthenticatedAppDokumenteIndexRouteImport } from './routes/_authenticated/app/dokumente/index'
import { Route as AuthenticatedAppDokumenteInvoiceIdRouteImport } from './routes/_authenticated/app/dokumente/$invoiceId'
import { Route as AuthenticatedAppDokumenteEinstellungenRouteImport } from './routes/_authenticated/app/dokumente/einstellungen'
import { Route as AuthenticatedAppKommunikationIndexRouteImport } from './routes/_authenticated/app/kommunikation/index'
import { Route as AuthenticatedAppKundenIndexRouteImport } from './routes/_authenticated/app/kunden/index'
import { Route as AuthenticatedAppKundenCustomerIdRouteImport } from './routes/_authenticated/app/kunden/$customerId'
import { Route as AuthenticatedAppLagerIndexRouteImport } from './routes/_authenticated/app/lager/index'
import { Route as AuthenticatedAppLagerBewegungenRouteImport } from './routes/_authenticated/app/lager/bewegungen'
import { Route as AuthenticatedAppLagerLagerorteRouteImport } from './routes/_authenticated/app/lager/lagerorte'
import { Route as AuthenticatedAppLagerReservierungenRouteImport } from './routes/_authenticated/app/lager/reservierungen'
import { Route as AuthenticatedAppLagerTransfersRouteImport } from './routes/_authenticated/app/lager/transfers'
import { Route as AuthenticatedAppLagerWareneingangRouteImport } from './routes/_authenticated/app/lager/wareneingang'
import { Route as AuthenticatedAppMarketingPromotionsRouteImport } from './routes/_authenticated/app/marketing/promotions'
import { Route as AuthenticatedAppPreiseIndexRouteImport } from './routes/_authenticated/app/preise/index'
import { Route as AuthenticatedAppPreiseTestenRouteImport } from './routes/_authenticated/app/preise/testen'
import { Route as AuthenticatedAppProdukteIndexRouteImport } from './routes/_authenticated/app/produkte/index'
import { Route as AuthenticatedAppProdukteProductIdRouteImport } from './routes/_authenticated/app/produkte/$productId'
import { Route as AuthenticatedAppProdukteNeuRouteImport } from './routes/_authenticated/app/produkte/neu'
import { Route as AuthenticatedAppRetourenIndexRouteImport } from './routes/_authenticated/app/retouren/index'
import { Route as AuthenticatedAppRetourenReturnIdRouteImport } from './routes/_authenticated/app/retouren/$returnId'
import { Route as AuthenticatedAppRetourenEinstellungenRouteImport } from './routes/_authenticated/app/retouren/einstellungen'
import { Route as AuthenticatedAppSystemStorefrontTestRouteImport } from './routes/_authenticated/app/system/storefront-test'
import { Route as AuthenticatedAppVersandIndexRouteImport } from './routes/_authenticated/app/versand/index'
import { Route as AuthenticatedAppVersandFulfillmentIdRouteImport } from './routes/_authenticated/app/versand/$fulfillmentId'
import { Route as AuthenticatedAppVersandDienstleisterRouteImport } from './routes/_authenticated/app/versand/dienstleister'
import { Route as AuthenticatedAppVersandVersandartenRouteImport } from './routes/_authenticated/app/versand/versandarten'
import { Route as ApiPublicJobsCommunicationsRouteImport } from './routes/api/public/jobs/communications'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksCarrierProviderRouteImport } from './routes/api/public/webhooks/carrier/$provider'
import { Route as ApiPublicWebhooksCommunicationsProviderRouteImport } from './routes/api/public/webhooks/communications/$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalGastRoute = PortalGastRouteImport.update({
  id: '/portal/gast',
  path: '/portal/gast',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppKategorienRoute =
  AuthenticatedAppKategorienRouteImport.update({
    id: '/app/kategorien',
    path: '/app/kategorien',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMedienRoute = AuthenticatedAppMedienRouteImport.update({
  id: '/app/medien',
  path: '/app/medien',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppShopsRoute = AuthenticatedAppShopsRouteImport.update({
  id: '/app/shops',
  path: '/app/shops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSteuernRoute = AuthenticatedAppSteuernRouteImport.update({
  id: '/app/steuern',
  path: '/app/steuern',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppWarenkoerbeRoute =
  AuthenticatedAppWarenkoerbeRouteImport.update({
    id: '/app/warenkoerbe',
    path: '/app/warenkoerbe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppZahlungenRoute =
  AuthenticatedAppZahlungenRouteImport.update({
    id: '/app/zahlungen',
    path: '/app/zahlungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PortalBestellungenOrderIdRoute =
  PortalBestellungenOrderIdRouteImport.update({
    id: '/portal/bestellungen/$orderId',
    path: '/portal/bestellungen/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppBestellungenIndexRoute =
  AuthenticatedAppBestellungenIndexRouteImport.update({
    id: '/app/bestellungen/',
    path: '/app/bestellungen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBestellungenOrderIdRoute =
  AuthenticatedAppBestellungenOrderIdRouteImport.update({
    id: '/app/bestellungen/$orderId',
    path: '/app/bestellungen/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDokumenteIndexRoute =
  AuthenticatedAppDokumenteIndexRouteImport.update({
    id: '/app/dokumente/',
    path: '/app/dokumente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDokumenteInvoiceIdRoute =
  AuthenticatedAppDokumenteInvoiceIdRouteImport.update({
    id: '/app/dokumente/$invoiceId',
    path: '/app/dokumente/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDokumenteEinstellungenRoute =
  AuthenticatedAppDokumenteEinstellungenRouteImport.update({
    id: '/app/dokumente/einstellungen',
    path: '/app/dokumente/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppKommunikationIndexRoute =
  AuthenticatedAppKommunikationIndexRouteImport.update({
    id: '/app/kommunikation/',
    path: '/app/kommunikation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppKundenIndexRoute =
  AuthenticatedAppKundenIndexRouteImport.update({
    id: '/app/kunden/',
    path: '/app/kunden/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppKundenCustomerIdRoute =
  AuthenticatedAppKundenCustomerIdRouteImport.update({
    id: '/app/kunden/$customerId',
    path: '/app/kunden/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerIndexRoute =
  AuthenticatedAppLagerIndexRouteImport.update({
    id: '/app/lager/',
    path: '/app/lager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerBewegungenRoute =
  AuthenticatedAppLagerBewegungenRouteImport.update({
    id: '/app/lager/bewegungen',
    path: '/app/lager/bewegungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerLagerorteRoute =
  AuthenticatedAppLagerLagerorteRouteImport.update({
    id: '/app/lager/lagerorte',
    path: '/app/lager/lagerorte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerReservierungenRoute =
  AuthenticatedAppLagerReservierungenRouteImport.update({
    id: '/app/lager/reservierungen',
    path: '/app/lager/reservierungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerTransfersRoute =
  AuthenticatedAppLagerTransfersRouteImport.update({
    id: '/app/lager/transfers',
    path: '/app/lager/transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLagerWareneingangRoute =
  AuthenticatedAppLagerWareneingangRouteImport.update({
    id: '/app/lager/wareneingang',
    path: '/app/lager/wareneingang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMarketingPromotionsRoute =
  AuthenticatedAppMarketingPromotionsRouteImport.update({
    id: '/app/marketing/promotions',
    path: '/app/marketing/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPreiseIndexRoute =
  AuthenticatedAppPreiseIndexRouteImport.update({
    id: '/app/preise/',
    path: '/app/preise/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPreiseTestenRoute =
  AuthenticatedAppPreiseTestenRouteImport.update({
    id: '/app/preise/testen',
    path: '/app/preise/testen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteIndexRoute =
  AuthenticatedAppProdukteIndexRouteImport.update({
    id: '/app/produkte/',
    path: '/app/produkte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteProductIdRoute =
  AuthenticatedAppProdukteProductIdRouteImport.update({
    id: '/app/produkte/$productId',
    path: '/app/produkte/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProdukteNeuRoute =
  AuthenticatedAppProdukteNeuRouteImport.update({
    id: '/app/produkte/neu',
    path: '/app/produkte/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRetourenIndexRoute =
  AuthenticatedAppRetourenIndexRouteImport.update({
    id: '/app/retouren/',
    path: '/app/retouren/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRetourenReturnIdRoute =
  AuthenticatedAppRetourenReturnIdRouteImport.update({
    id: '/app/retouren/$returnId',
    path: '/app/retouren/$returnId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRetourenEinstellungenRoute =
  AuthenticatedAppRetourenEinstellungenRouteImport.update({
    id: '/app/retouren/einstellungen',
    path: '/app/retouren/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSystemStorefrontTestRoute =
  AuthenticatedAppSystemStorefrontTestRouteImport.update({
    id: '/app/system/storefront-test',
    path: '/app/system/storefront-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVersandIndexRoute =
  AuthenticatedAppVersandIndexRouteImport.update({
    id: '/app/versand/',
    path: '/app/versand/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVersandFulfillmentIdRoute =
  AuthenticatedAppVersandFulfillmentIdRouteImport.update({
    id: '/app/versand/$fulfillmentId',
    path: '/app/versand/$fulfillmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVersandDienstleisterRoute =
  AuthenticatedAppVersandDienstleisterRouteImport.update({
    id: '/app/versand/dienstleister',
    path: '/app/versand/dienstleister',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVersandVersandartenRoute =
  AuthenticatedAppVersandVersandartenRouteImport.update({
    id: '/app/versand/versandarten',
    path: '/app/versand/versandarten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicJobsCommunicationsRoute =
  ApiPublicJobsCommunicationsRouteImport.update({
    id: '/api/public/jobs/communications',
    path: '/api/public/jobs/communications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCarrierProviderRoute =
  ApiPublicWebhooksCarrierProviderRouteImport.update({
    id: '/api/public/webhooks/carrier/$provider',
    path: '/api/public/webhooks/carrier/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCommunicationsProviderRoute =
  ApiPublicWebhooksCommunicationsProviderRouteImport.update({
    id: '/api/public/webhooks/communications/$provider',
    path: '/api/public/webhooks/communications/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/portal/gast': typeof PortalGastRoute
  '/portal/': typeof PortalIndexRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/app/medien': typeof AuthenticatedAppMedienRoute
  '/app/shops': typeof AuthenticatedAppShopsRoute
  '/app/steuern': typeof AuthenticatedAppSteuernRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/warenkoerbe': typeof AuthenticatedAppWarenkoerbeRoute
  '/app/zahlungen': typeof AuthenticatedAppZahlungenRoute
  '/portal/bestellungen/$orderId': typeof PortalBestellungenOrderIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/bestellungen/$orderId': typeof AuthenticatedAppBestellungenOrderIdRoute
  '/app/dokumente/$invoiceId': typeof AuthenticatedAppDokumenteInvoiceIdRoute
  '/app/dokumente/einstellungen': typeof AuthenticatedAppDokumenteEinstellungenRoute
  '/app/kunden/$customerId': typeof AuthenticatedAppKundenCustomerIdRoute
  '/app/lager/bewegungen': typeof AuthenticatedAppLagerBewegungenRoute
  '/app/lager/lagerorte': typeof AuthenticatedAppLagerLagerorteRoute
  '/app/lager/reservierungen': typeof AuthenticatedAppLagerReservierungenRoute
  '/app/lager/transfers': typeof AuthenticatedAppLagerTransfersRoute
  '/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/app/retouren/$returnId': typeof AuthenticatedAppRetourenReturnIdRoute
  '/app/retouren/einstellungen': typeof AuthenticatedAppRetourenEinstellungenRoute
  '/app/system/storefront-test': typeof AuthenticatedAppSystemStorefrontTestRoute
  '/app/versand/$fulfillmentId': typeof AuthenticatedAppVersandFulfillmentIdRoute
  '/app/versand/dienstleister': typeof AuthenticatedAppVersandDienstleisterRoute
  '/app/versand/versandarten': typeof AuthenticatedAppVersandVersandartenRoute
  '/api/public/jobs/communications': typeof ApiPublicJobsCommunicationsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/bestellungen/': typeof AuthenticatedAppBestellungenIndexRoute
  '/app/dokumente/': typeof AuthenticatedAppDokumenteIndexRoute
  '/app/kommunikation/': typeof AuthenticatedAppKommunikationIndexRoute
  '/app/kunden/': typeof AuthenticatedAppKundenIndexRoute
  '/app/lager/': typeof AuthenticatedAppLagerIndexRoute
  '/app/preise/': typeof AuthenticatedAppPreiseIndexRoute
  '/app/produkte/': typeof AuthenticatedAppProdukteIndexRoute
  '/app/retouren/': typeof AuthenticatedAppRetourenIndexRoute
  '/app/versand/': typeof AuthenticatedAppVersandIndexRoute
  '/api/public/webhooks/carrier/$provider': typeof ApiPublicWebhooksCarrierProviderRoute
  '/api/public/webhooks/communications/$provider': typeof ApiPublicWebhooksCommunicationsProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/portal/gast': typeof PortalGastRoute
  '/portal': typeof PortalIndexRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/app/medien': typeof AuthenticatedAppMedienRoute
  '/app/shops': typeof AuthenticatedAppShopsRoute
  '/app/steuern': typeof AuthenticatedAppSteuernRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/warenkoerbe': typeof AuthenticatedAppWarenkoerbeRoute
  '/app/zahlungen': typeof AuthenticatedAppZahlungenRoute
  '/portal/bestellungen/$orderId': typeof PortalBestellungenOrderIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/bestellungen/$orderId': typeof AuthenticatedAppBestellungenOrderIdRoute
  '/app/dokumente/$invoiceId': typeof AuthenticatedAppDokumenteInvoiceIdRoute
  '/app/dokumente/einstellungen': typeof AuthenticatedAppDokumenteEinstellungenRoute
  '/app/kunden/$customerId': typeof AuthenticatedAppKundenCustomerIdRoute
  '/app/lager/bewegungen': typeof AuthenticatedAppLagerBewegungenRoute
  '/app/lager/lagerorte': typeof AuthenticatedAppLagerLagerorteRoute
  '/app/lager/reservierungen': typeof AuthenticatedAppLagerReservierungenRoute
  '/app/lager/transfers': typeof AuthenticatedAppLagerTransfersRoute
  '/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/app/retouren/$returnId': typeof AuthenticatedAppRetourenReturnIdRoute
  '/app/retouren/einstellungen': typeof AuthenticatedAppRetourenEinstellungenRoute
  '/app/system/storefront-test': typeof AuthenticatedAppSystemStorefrontTestRoute
  '/app/versand/$fulfillmentId': typeof AuthenticatedAppVersandFulfillmentIdRoute
  '/app/versand/dienstleister': typeof AuthenticatedAppVersandDienstleisterRoute
  '/app/versand/versandarten': typeof AuthenticatedAppVersandVersandartenRoute
  '/api/public/jobs/communications': typeof ApiPublicJobsCommunicationsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/bestellungen': typeof AuthenticatedAppBestellungenIndexRoute
  '/app/dokumente': typeof AuthenticatedAppDokumenteIndexRoute
  '/app/kommunikation': typeof AuthenticatedAppKommunikationIndexRoute
  '/app/kunden': typeof AuthenticatedAppKundenIndexRoute
  '/app/lager': typeof AuthenticatedAppLagerIndexRoute
  '/app/preise': typeof AuthenticatedAppPreiseIndexRoute
  '/app/produkte': typeof AuthenticatedAppProdukteIndexRoute
  '/app/retouren': typeof AuthenticatedAppRetourenIndexRoute
  '/app/versand': typeof AuthenticatedAppVersandIndexRoute
  '/api/public/webhooks/carrier/$provider': typeof ApiPublicWebhooksCarrierProviderRoute
  '/api/public/webhooks/communications/$provider': typeof ApiPublicWebhooksCommunicationsProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/portal/gast': typeof PortalGastRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/kategorien': typeof AuthenticatedAppKategorienRoute
  '/_authenticated/app/medien': typeof AuthenticatedAppMedienRoute
  '/_authenticated/app/shops': typeof AuthenticatedAppShopsRoute
  '/_authenticated/app/steuern': typeof AuthenticatedAppSteuernRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/warenkoerbe': typeof AuthenticatedAppWarenkoerbeRoute
  '/_authenticated/app/zahlungen': typeof AuthenticatedAppZahlungenRoute
  '/portal/bestellungen/$orderId': typeof PortalBestellungenOrderIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/bestellungen/$orderId': typeof AuthenticatedAppBestellungenOrderIdRoute
  '/_authenticated/app/dokumente/$invoiceId': typeof AuthenticatedAppDokumenteInvoiceIdRoute
  '/_authenticated/app/dokumente/einstellungen': typeof AuthenticatedAppDokumenteEinstellungenRoute
  '/_authenticated/app/kunden/$customerId': typeof AuthenticatedAppKundenCustomerIdRoute
  '/_authenticated/app/lager/bewegungen': typeof AuthenticatedAppLagerBewegungenRoute
  '/_authenticated/app/lager/lagerorte': typeof AuthenticatedAppLagerLagerorteRoute
  '/_authenticated/app/lager/reservierungen': typeof AuthenticatedAppLagerReservierungenRoute
  '/_authenticated/app/lager/transfers': typeof AuthenticatedAppLagerTransfersRoute
  '/_authenticated/app/lager/wareneingang': typeof AuthenticatedAppLagerWareneingangRoute
  '/_authenticated/app/marketing/promotions': typeof AuthenticatedAppMarketingPromotionsRoute
  '/_authenticated/app/preise/testen': typeof AuthenticatedAppPreiseTestenRoute
  '/_authenticated/app/produkte/$productId': typeof AuthenticatedAppProdukteProductIdRoute
  '/_authenticated/app/produkte/neu': typeof AuthenticatedAppProdukteNeuRoute
  '/_authenticated/app/retouren/$returnId': typeof AuthenticatedAppRetourenReturnIdRoute
  '/_authenticated/app/retouren/einstellungen': typeof AuthenticatedAppRetourenEinstellungenRoute
  '/_authenticated/app/system/storefront-test': typeof AuthenticatedAppSystemStorefrontTestRoute
  '/_authenticated/app/versand/$fulfillmentId': typeof AuthenticatedAppVersandFulfillmentIdRoute
  '/_authenticated/app/versand/dienstleister': typeof AuthenticatedAppVersandDienstleisterRoute
  '/_authenticated/app/versand/versandarten': typeof AuthenticatedAppVersandVersandartenRoute
  '/api/public/jobs/communications': typeof ApiPublicJobsCommunicationsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/_authenticated/app/bestellungen/': typeof AuthenticatedAppBestellungenIndexRoute
  '/_authenticated/app/dokumente/': typeof AuthenticatedAppDokumenteIndexRoute
  '/_authenticated/app/kommunikation/': typeof AuthenticatedAppKommunikationIndexRoute
  '/_authenticated/app/kunden/': typeof AuthenticatedAppKundenIndexRoute
  '/_authenticated/app/lager/': typeof AuthenticatedAppLagerIndexRoute
  '/_authenticated/app/preise/': typeof AuthenticatedAppPreiseIndexRoute
  '/_authenticated/app/produkte/': typeof AuthenticatedAppProdukteIndexRoute
  '/_authenticated/app/retouren/': typeof AuthenticatedAppRetourenIndexRoute
  '/_authenticated/app/versand/': typeof AuthenticatedAppVersandIndexRoute
  '/api/public/webhooks/carrier/$provider': typeof ApiPublicWebhooksCarrierProviderRoute
  '/api/public/webhooks/communications/$provider': typeof ApiPublicWebhooksCommunicationsProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite'
    | '/portal/gast'
    | '/portal/'
    | '/app/audit'
    | '/app/kategorien'
    | '/app/medien'
    | '/app/shops'
    | '/app/steuern'
    | '/app/team'
    | '/app/warenkoerbe'
    | '/app/zahlungen'
    | '/portal/bestellungen/$orderId'
    | '/app/'
    | '/app/bestellungen/$orderId'
    | '/app/dokumente/$invoiceId'
    | '/app/dokumente/einstellungen'
    | '/app/kunden/$customerId'
    | '/app/lager/bewegungen'
    | '/app/lager/lagerorte'
    | '/app/lager/reservierungen'
    | '/app/lager/transfers'
    | '/app/lager/wareneingang'
    | '/app/marketing/promotions'
    | '/app/preise/testen'
    | '/app/produkte/$productId'
    | '/app/produkte/neu'
    | '/app/retouren/$returnId'
    | '/app/retouren/einstellungen'
    | '/app/system/storefront-test'
    | '/app/versand/$fulfillmentId'
    | '/app/versand/dienstleister'
    | '/app/versand/versandarten'
    | '/api/public/jobs/communications'
    | '/api/public/webhooks/stripe'
    | '/app/bestellungen/'
    | '/app/dokumente/'
    | '/app/kommunikation/'
    | '/app/kunden/'
    | '/app/lager/'
    | '/app/preise/'
    | '/app/produkte/'
    | '/app/retouren/'
    | '/app/versand/'
    | '/api/public/webhooks/carrier/$provider'
    | '/api/public/webhooks/communications/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/portal/gast'
    | '/portal'
    | '/app/audit'
    | '/app/kategorien'
    | '/app/medien'
    | '/app/shops'
    | '/app/steuern'
    | '/app/team'
    | '/app/warenkoerbe'
    | '/app/zahlungen'
    | '/portal/bestellungen/$orderId'
    | '/app'
    | '/app/bestellungen/$orderId'
    | '/app/dokumente/$invoiceId'
    | '/app/dokumente/einstellungen'
    | '/app/kunden/$customerId'
    | '/app/lager/bewegungen'
    | '/app/lager/lagerorte'
    | '/app/lager/reservierungen'
    | '/app/lager/transfers'
    | '/app/lager/wareneingang'
    | '/app/marketing/promotions'
    | '/app/preise/testen'
    | '/app/produkte/$productId'
    | '/app/produkte/neu'
    | '/app/retouren/$returnId'
    | '/app/retouren/einstellungen'
    | '/app/system/storefront-test'
    | '/app/versand/$fulfillmentId'
    | '/app/versand/dienstleister'
    | '/app/versand/versandarten'
    | '/api/public/jobs/communications'
    | '/api/public/webhooks/stripe'
    | '/app/bestellungen'
    | '/app/dokumente'
    | '/app/kommunikation'
    | '/app/kunden'
    | '/app/lager'
    | '/app/preise'
    | '/app/produkte'
    | '/app/retouren'
    | '/app/versand'
    | '/api/public/webhooks/carrier/$provider'
    | '/api/public/webhooks/communications/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/invite'
    | '/portal/gast'
    | '/portal/'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/kategorien'
    | '/_authenticated/app/medien'
    | '/_authenticated/app/shops'
    | '/_authenticated/app/steuern'
    | '/_authenticated/app/team'
    | '/_authenticated/app/warenkoerbe'
    | '/_authenticated/app/zahlungen'
    | '/portal/bestellungen/$orderId'
    | '/_authenticated/app/'
    | '/_authenticated/app/bestellungen/$orderId'
    | '/_authenticated/app/dokumente/$invoiceId'
    | '/_authenticated/app/dokumente/einstellungen'
    | '/_authenticated/app/kunden/$customerId'
    | '/_authenticated/app/lager/bewegungen'
    | '/_authenticated/app/lager/lagerorte'
    | '/_authenticated/app/lager/reservierungen'
    | '/_authenticated/app/lager/transfers'
    | '/_authenticated/app/lager/wareneingang'
    | '/_authenticated/app/marketing/promotions'
    | '/_authenticated/app/preise/testen'
    | '/_authenticated/app/produkte/$productId'
    | '/_authenticated/app/produkte/neu'
    | '/_authenticated/app/retouren/$returnId'
    | '/_authenticated/app/retouren/einstellungen'
    | '/_authenticated/app/system/storefront-test'
    | '/_authenticated/app/versand/$fulfillmentId'
    | '/_authenticated/app/versand/dienstleister'
    | '/_authenticated/app/versand/versandarten'
    | '/api/public/jobs/communications'
    | '/api/public/webhooks/stripe'
    | '/_authenticated/app/bestellungen/'
    | '/_authenticated/app/dokumente/'
    | '/_authenticated/app/kommunikation/'
    | '/_authenticated/app/kunden/'
    | '/_authenticated/app/lager/'
    | '/_authenticated/app/preise/'
    | '/_authenticated/app/produkte/'
    | '/_authenticated/app/retouren/'
    | '/_authenticated/app/versand/'
    | '/api/public/webhooks/carrier/$provider'
    | '/api/public/webhooks/communications/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteRoute: typeof InviteRoute
  PortalGastRoute: typeof PortalGastRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalBestellungenOrderIdRoute: typeof PortalBestellungenOrderIdRoute
  ApiPublicJobsCommunicationsRoute: typeof ApiPublicJobsCommunicationsRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicWebhooksCarrierProviderRoute: typeof ApiPublicWebhooksCarrierProviderRoute
  ApiPublicWebhooksCommunicationsProviderRoute: typeof ApiPublicWebhooksCommunicationsProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/gast': {
      id: '/portal/gast'
      path: '/portal/gast'
      fullPath: '/portal/gast'
      preLoaderRoute: typeof PortalGastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kategorien': {
      id: '/_authenticated/app/kategorien'
      path: '/app/kategorien'
      fullPath: '/app/kategorien'
      preLoaderRoute: typeof AuthenticatedAppKategorienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/medien': {
      id: '/_authenticated/app/medien'
      path: '/app/medien'
      fullPath: '/app/medien'
      preLoaderRoute: typeof AuthenticatedAppMedienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/shops': {
      id: '/_authenticated/app/shops'
      path: '/app/shops'
      fullPath: '/app/shops'
      preLoaderRoute: typeof AuthenticatedAppShopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/steuern': {
      id: '/_authenticated/app/steuern'
      path: '/app/steuern'
      fullPath: '/app/steuern'
      preLoaderRoute: typeof AuthenticatedAppSteuernRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/warenkoerbe': {
      id: '/_authenticated/app/warenkoerbe'
      path: '/app/warenkoerbe'
      fullPath: '/app/warenkoerbe'
      preLoaderRoute: typeof AuthenticatedAppWarenkoerbeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/zahlungen': {
      id: '/_authenticated/app/zahlungen'
      path: '/app/zahlungen'
      fullPath: '/app/zahlungen'
      preLoaderRoute: typeof AuthenticatedAppZahlungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/bestellungen/$orderId': {
      id: '/portal/bestellungen/$orderId'
      path: '/portal/bestellungen/$orderId'
      fullPath: '/portal/bestellungen/$orderId'
      preLoaderRoute: typeof PortalBestellungenOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/bestellungen/': {
      id: '/_authenticated/app/bestellungen/'
      path: '/app/bestellungen'
      fullPath: '/app/bestellungen/'
      preLoaderRoute: typeof AuthenticatedAppBestellungenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bestellungen/$orderId': {
      id: '/_authenticated/app/bestellungen/$orderId'
      path: '/app/bestellungen/$orderId'
      fullPath: '/app/bestellungen/$orderId'
      preLoaderRoute: typeof AuthenticatedAppBestellungenOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dokumente/': {
      id: '/_authenticated/app/dokumente/'
      path: '/app/dokumente'
      fullPath: '/app/dokumente/'
      preLoaderRoute: typeof AuthenticatedAppDokumenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dokumente/$invoiceId': {
      id: '/_authenticated/app/dokumente/$invoiceId'
      path: '/app/dokumente/$invoiceId'
      fullPath: '/app/dokumente/$invoiceId'
      preLoaderRoute: typeof AuthenticatedAppDokumenteInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dokumente/einstellungen': {
      id: '/_authenticated/app/dokumente/einstellungen'
      path: '/app/dokumente/einstellungen'
      fullPath: '/app/dokumente/einstellungen'
      preLoaderRoute: typeof AuthenticatedAppDokumenteEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kommunikation/': {
      id: '/_authenticated/app/kommunikation/'
      path: '/app/kommunikation'
      fullPath: '/app/kommunikation/'
      preLoaderRoute: typeof AuthenticatedAppKommunikationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kunden/': {
      id: '/_authenticated/app/kunden/'
      path: '/app/kunden'
      fullPath: '/app/kunden/'
      preLoaderRoute: typeof AuthenticatedAppKundenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kunden/$customerId': {
      id: '/_authenticated/app/kunden/$customerId'
      path: '/app/kunden/$customerId'
      fullPath: '/app/kunden/$customerId'
      preLoaderRoute: typeof AuthenticatedAppKundenCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/': {
      id: '/_authenticated/app/lager/'
      path: '/app/lager'
      fullPath: '/app/lager/'
      preLoaderRoute: typeof AuthenticatedAppLagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/bewegungen': {
      id: '/_authenticated/app/lager/bewegungen'
      path: '/app/lager/bewegungen'
      fullPath: '/app/lager/bewegungen'
      preLoaderRoute: typeof AuthenticatedAppLagerBewegungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/lagerorte': {
      id: '/_authenticated/app/lager/lagerorte'
      path: '/app/lager/lagerorte'
      fullPath: '/app/lager/lagerorte'
      preLoaderRoute: typeof AuthenticatedAppLagerLagerorteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/reservierungen': {
      id: '/_authenticated/app/lager/reservierungen'
      path: '/app/lager/reservierungen'
      fullPath: '/app/lager/reservierungen'
      preLoaderRoute: typeof AuthenticatedAppLagerReservierungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/transfers': {
      id: '/_authenticated/app/lager/transfers'
      path: '/app/lager/transfers'
      fullPath: '/app/lager/transfers'
      preLoaderRoute: typeof AuthenticatedAppLagerTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lager/wareneingang': {
      id: '/_authenticated/app/lager/wareneingang'
      path: '/app/lager/wareneingang'
      fullPath: '/app/lager/wareneingang'
      preLoaderRoute: typeof AuthenticatedAppLagerWareneingangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/marketing/promotions': {
      id: '/_authenticated/app/marketing/promotions'
      path: '/app/marketing/promotions'
      fullPath: '/app/marketing/promotions'
      preLoaderRoute: typeof AuthenticatedAppMarketingPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/preise/': {
      id: '/_authenticated/app/preise/'
      path: '/app/preise'
      fullPath: '/app/preise/'
      preLoaderRoute: typeof AuthenticatedAppPreiseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/preise/testen': {
      id: '/_authenticated/app/preise/testen'
      path: '/app/preise/testen'
      fullPath: '/app/preise/testen'
      preLoaderRoute: typeof AuthenticatedAppPreiseTestenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/': {
      id: '/_authenticated/app/produkte/'
      path: '/app/produkte'
      fullPath: '/app/produkte/'
      preLoaderRoute: typeof AuthenticatedAppProdukteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/$productId': {
      id: '/_authenticated/app/produkte/$productId'
      path: '/app/produkte/$productId'
      fullPath: '/app/produkte/$productId'
      preLoaderRoute: typeof AuthenticatedAppProdukteProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/produkte/neu': {
      id: '/_authenticated/app/produkte/neu'
      path: '/app/produkte/neu'
      fullPath: '/app/produkte/neu'
      preLoaderRoute: typeof AuthenticatedAppProdukteNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/retouren/': {
      id: '/_authenticated/app/retouren/'
      path: '/app/retouren'
      fullPath: '/app/retouren/'
      preLoaderRoute: typeof AuthenticatedAppRetourenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/retouren/$returnId': {
      id: '/_authenticated/app/retouren/$returnId'
      path: '/app/retouren/$returnId'
      fullPath: '/app/retouren/$returnId'
      preLoaderRoute: typeof AuthenticatedAppRetourenReturnIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/retouren/einstellungen': {
      id: '/_authenticated/app/retouren/einstellungen'
      path: '/app/retouren/einstellungen'
      fullPath: '/app/retouren/einstellungen'
      preLoaderRoute: typeof AuthenticatedAppRetourenEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/system/storefront-test': {
      id: '/_authenticated/app/system/storefront-test'
      path: '/app/system/storefront-test'
      fullPath: '/app/system/storefront-test'
      preLoaderRoute: typeof AuthenticatedAppSystemStorefrontTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/versand/': {
      id: '/_authenticated/app/versand/'
      path: '/app/versand'
      fullPath: '/app/versand/'
      preLoaderRoute: typeof AuthenticatedAppVersandIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/versand/$fulfillmentId': {
      id: '/_authenticated/app/versand/$fulfillmentId'
      path: '/app/versand/$fulfillmentId'
      fullPath: '/app/versand/$fulfillmentId'
      preLoaderRoute: typeof AuthenticatedAppVersandFulfillmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/versand/dienstleister': {
      id: '/_authenticated/app/versand/dienstleister'
      path: '/app/versand/dienstleister'
      fullPath: '/app/versand/dienstleister'
      preLoaderRoute: typeof AuthenticatedAppVersandDienstleisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/versand/versandarten': {
      id: '/_authenticated/app/versand/versandarten'
      path: '/app/versand/versandarten'
      fullPath: '/app/versand/versandarten'
      preLoaderRoute: typeof AuthenticatedAppVersandVersandartenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/jobs/communications': {
      id: '/api/public/jobs/communications'
      path: '/api/public/jobs/communications'
      fullPath: '/api/public/jobs/communications'
      preLoaderRoute: typeof ApiPublicJobsCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/carrier/$provider': {
      id: '/api/public/webhooks/carrier/$provider'
      path: '/api/public/webhooks/carrier/$provider'
      fullPath: '/api/public/webhooks/carrier/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksCarrierProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/communications/$provider': {
      id: '/api/public/webhooks/communications/$provider'
      path: '/api/public/webhooks/communications/$provider'
      fullPath: '/api/public/webhooks/communications/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksCommunicationsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppKategorienRoute: typeof AuthenticatedAppKategorienRoute
  AuthenticatedAppMedienRoute: typeof AuthenticatedAppMedienRoute
  AuthenticatedAppShopsRoute: typeof AuthenticatedAppShopsRoute
  AuthenticatedAppSteuernRoute: typeof AuthenticatedAppSteuernRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppWarenkoerbeRoute: typeof AuthenticatedAppWarenkoerbeRoute
  AuthenticatedAppZahlungenRoute: typeof AuthenticatedAppZahlungenRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBestellungenOrderIdRoute: typeof AuthenticatedAppBestellungenOrderIdRoute
  AuthenticatedAppDokumenteInvoiceIdRoute: typeof AuthenticatedAppDokumenteInvoiceIdRoute
  AuthenticatedAppDokumenteEinstellungenRoute: typeof AuthenticatedAppDokumenteEinstellungenRoute
  AuthenticatedAppKundenCustomerIdRoute: typeof AuthenticatedAppKundenCustomerIdRoute
  AuthenticatedAppLagerBewegungenRoute: typeof AuthenticatedAppLagerBewegungenRoute
  AuthenticatedAppLagerLagerorteRoute: typeof AuthenticatedAppLagerLagerorteRoute
  AuthenticatedAppLagerReservierungenRoute: typeof AuthenticatedAppLagerReservierungenRoute
  AuthenticatedAppLagerTransfersRoute: typeof AuthenticatedAppLagerTransfersRoute
  AuthenticatedAppLagerWareneingangRoute: typeof AuthenticatedAppLagerWareneingangRoute
  AuthenticatedAppMarketingPromotionsRoute: typeof AuthenticatedAppMarketingPromotionsRoute
  AuthenticatedAppPreiseTestenRoute: typeof AuthenticatedAppPreiseTestenRoute
  AuthenticatedAppProdukteProductIdRoute: typeof AuthenticatedAppProdukteProductIdRoute
  AuthenticatedAppProdukteNeuRoute: typeof AuthenticatedAppProdukteNeuRoute
  AuthenticatedAppRetourenReturnIdRoute: typeof AuthenticatedAppRetourenReturnIdRoute
  AuthenticatedAppRetourenEinstellungenRoute: typeof AuthenticatedAppRetourenEinstellungenRoute
  AuthenticatedAppSystemStorefrontTestRoute: typeof AuthenticatedAppSystemStorefrontTestRoute
  AuthenticatedAppVersandFulfillmentIdRoute: typeof AuthenticatedAppVersandFulfillmentIdRoute
  AuthenticatedAppVersandDienstleisterRoute: typeof AuthenticatedAppVersandDienstleisterRoute
  AuthenticatedAppVersandVersandartenRoute: typeof AuthenticatedAppVersandVersandartenRoute
  AuthenticatedAppBestellungenIndexRoute: typeof AuthenticatedAppBestellungenIndexRoute
  AuthenticatedAppDokumenteIndexRoute: typeof AuthenticatedAppDokumenteIndexRoute
  AuthenticatedAppKommunikationIndexRoute: typeof AuthenticatedAppKommunikationIndexRoute
  AuthenticatedAppKundenIndexRoute: typeof AuthenticatedAppKundenIndexRoute
  AuthenticatedAppLagerIndexRoute: typeof AuthenticatedAppLagerIndexRoute
  AuthenticatedAppPreiseIndexRoute: typeof AuthenticatedAppPreiseIndexRoute
  AuthenticatedAppProdukteIndexRoute: typeof AuthenticatedAppProdukteIndexRoute
  AuthenticatedAppRetourenIndexRoute: typeof AuthenticatedAppRetourenIndexRoute
  AuthenticatedAppVersandIndexRoute: typeof AuthenticatedAppVersandIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppKategorienRoute: AuthenticatedAppKategorienRoute,
  AuthenticatedAppMedienRoute: AuthenticatedAppMedienRoute,
  AuthenticatedAppShopsRoute: AuthenticatedAppShopsRoute,
  AuthenticatedAppSteuernRoute: AuthenticatedAppSteuernRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppWarenkoerbeRoute: AuthenticatedAppWarenkoerbeRoute,
  AuthenticatedAppZahlungenRoute: AuthenticatedAppZahlungenRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBestellungenOrderIdRoute:
    AuthenticatedAppBestellungenOrderIdRoute,
  AuthenticatedAppDokumenteInvoiceIdRoute:
    AuthenticatedAppDokumenteInvoiceIdRoute,
  AuthenticatedAppDokumenteEinstellungenRoute:
    AuthenticatedAppDokumenteEinstellungenRoute,
  AuthenticatedAppKundenCustomerIdRoute: AuthenticatedAppKundenCustomerIdRoute,
  AuthenticatedAppLagerBewegungenRoute: AuthenticatedAppLagerBewegungenRoute,
  AuthenticatedAppLagerLagerorteRoute: AuthenticatedAppLagerLagerorteRoute,
  AuthenticatedAppLagerReservierungenRoute:
    AuthenticatedAppLagerReservierungenRoute,
  AuthenticatedAppLagerTransfersRoute: AuthenticatedAppLagerTransfersRoute,
  AuthenticatedAppLagerWareneingangRoute:
    AuthenticatedAppLagerWareneingangRoute,
  AuthenticatedAppMarketingPromotionsRoute:
    AuthenticatedAppMarketingPromotionsRoute,
  AuthenticatedAppPreiseTestenRoute: AuthenticatedAppPreiseTestenRoute,
  AuthenticatedAppProdukteProductIdRoute:
    AuthenticatedAppProdukteProductIdRoute,
  AuthenticatedAppProdukteNeuRoute: AuthenticatedAppProdukteNeuRoute,
  AuthenticatedAppRetourenReturnIdRoute: AuthenticatedAppRetourenReturnIdRoute,
  AuthenticatedAppRetourenEinstellungenRoute:
    AuthenticatedAppRetourenEinstellungenRoute,
  AuthenticatedAppSystemStorefrontTestRoute:
    AuthenticatedAppSystemStorefrontTestRoute,
  AuthenticatedAppVersandFulfillmentIdRoute:
    AuthenticatedAppVersandFulfillmentIdRoute,
  AuthenticatedAppVersandDienstleisterRoute:
    AuthenticatedAppVersandDienstleisterRoute,
  AuthenticatedAppVersandVersandartenRoute:
    AuthenticatedAppVersandVersandartenRoute,
  AuthenticatedAppBestellungenIndexRoute:
    AuthenticatedAppBestellungenIndexRoute,
  AuthenticatedAppDokumenteIndexRoute: AuthenticatedAppDokumenteIndexRoute,
  AuthenticatedAppKommunikationIndexRoute:
    AuthenticatedAppKommunikationIndexRoute,
  AuthenticatedAppKundenIndexRoute: AuthenticatedAppKundenIndexRoute,
  AuthenticatedAppLagerIndexRoute: AuthenticatedAppLagerIndexRoute,
  AuthenticatedAppPreiseIndexRoute: AuthenticatedAppPreiseIndexRoute,
  AuthenticatedAppProdukteIndexRoute: AuthenticatedAppProdukteIndexRoute,
  AuthenticatedAppRetourenIndexRoute: AuthenticatedAppRetourenIndexRoute,
  AuthenticatedAppVersandIndexRoute: AuthenticatedAppVersandIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteRoute: InviteRoute,
  PortalGastRoute: PortalGastRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalBestellungenOrderIdRoute: PortalBestellungenOrderIdRoute,
  ApiPublicJobsCommunicationsRoute: ApiPublicJobsCommunicationsRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicWebhooksCarrierProviderRoute: ApiPublicWebhooksCarrierProviderRoute,
  ApiPublicWebhooksCommunicationsProviderRoute:
    ApiPublicWebhooksCommunicationsProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
